### ISSUE TITLE
add repo "About" metadata

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/membrane-curvature#1]
To make it more obvious what this repo is about, I suggest to
- [x] update the description of the repo (the _About_ setting on the repo front page)
- [x] add a link to your blog (also _About_(

**Comment by ojeda-e** [comment]
Thanks. Description and link to my blog in the about section added.

**Comment by lilyminium** [comment]
This might be a silly question, but where is the About section? I can't seem to find it 😅

**Comment by ojeda-e** [comment]
> This might be a silly question, but where is the About section? I can't seem to find it 😅

I think it is the section where you can edit the details of the repo, at the top right corner in the [code](https://github.com/MDAnalysis/membrane-curvature) page.

**Comment by lilyminium** [comment]
Ohhhh thank you! I think you've done this then, would you like to close your first issue? :D

**Comment by ojeda-e** [comment]
Repo description and link to blog in the about section added.
