### ISSUE TITLE
PyPi wheels & sdist contain extra user generated files & breaking tests

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/membrane-curvature#123]
The wheels & distribution on pypi include:

- membrane_curvature/MDAnalysis.log
- membrane_curvature/htmlcov
- membrane_cruvature/tests/htmlcov

These are a) breaking tests if you try to do `pytest --pyargs membrane_curvature.tests` and also b) adding roughly ~ 1 MB of extra stuff that doesn't need to be there.

**Comment by IAlibay** [comment]
@ojeda-e I think this might be due to using a non-clean local copy for creating wheel & sdist.

My suggestion here is:

a) To add an OIDC-enabled deployment workflow, e.g. "just push tags and it'll upload automatically"
b) Create a new bugfix release with the relevant files removed.

Happy to take this on if it sounds reasonable.

**Comment by ojeda-e** [comment]
Hi @IAlibay thanks for pointing this out, if you are available to work on this I'd appreciate it. I'll resume work on the repo after Thursday.

**Comment by IAlibay** [comment]
This is fixed with 1.1.1
