### ISSUE TITLE
Create more specific issues and add to suitable milestones

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/membrane-curvature#17]
As #13 notes, while it introduces some initial tests for the final result of each curvature function, additional and more specific intermediate tests (e.g. for getting the z-coordinates from a particular trajectory) will be added. In order to keep an eye on progress with the automated project tracker (https://github.com/MDAnalysis/membrane-curvature/projects/1), perhaps you could create some more issues for what you plan to do in the coming weeks, @ojeda-e?

For example, instead of "write tests for MDTraj code", an issue could be "write tests for the core_fast_* functions" (and add it to the [MDTraj](https://github.com/MDAnalysis/membrane-curvature/milestone/2) milestone). You could also look further ahead and start planning the structure of the MDAnalysis re-factor -- which functions you want to do first, etc.

~I *think* the project will automatically track created issues and PR's, so the only manual work is adding labels and/or milestones.~ Edit: sorry, you will have to manually add issues and PR's to the project tracker and milestones. This is quite a lot of project management so let us know if it gets too redundant and you prefer one or the other -- I am new to GitHub project management too!

I do like milestones because they have deadlines, so you can see how you're going in a particular area time-wise. They're usually overarching goals that have many issues and PR's attached (e.g. MDAnalysis uses them for [releases](https://github.com/MDAnalysis/mdanalysis/milestone/16)). I would guess that "MDAnalysis refactor" would be the next big one. The milestones tab can be a bit hard to find so I will just it here: https://github.com/MDAnalysis/membrane-curvature/milestones?direction=asc&sort=due_date

**Comment by ojeda-e** [comment]
I have created more specific issues, all of them assigned to their respective milestones and properly labeled. At least to what I can see in the short term. I could add long term ones, but will be very likely changed/replace for others.
Should I keep this issue open @lilyminium?

**Comment by ojeda-e** [comment]
After deleting unnecessary/unused lines in PR #29, coverage was increased by 15.92%.

**Comment by lilyminium** [comment]
Thanks @ojeda-e for opening the new issues, with these and the plans you showed us in your presentation I think this issue is good to close :-)

**Comment by ojeda-e** [comment]
Thanks @lilyminium :)
