### ISSUE TITLE
Use explicit imports - change location of `lib/mods.py` 

### ISSUE THREAD

**Issue by ojeda-e** [MDAnalysis/membrane-curvature#21]
As suggested in https://github.com/MDAnalysis/membrane-curvature/pull/13#discussion_r651377651, 
it's better to use explicit imports, which makes the code easier to debug and to read. The preferred form to use is `import y` and then use `y.x`.

To do:
- [ ] Change location of `libs/mods.py`
- [ ] Use explicit import in `core.py`.
- [ ] Use explicit import in `tests/test_mdakit_membcurv.py`

**Comment by ojeda-e** [comment]
I have a question now that I review this issue. 
Would it make sense if I change the current structure of `membrane_curvature `
```
membrane_curvature
├── __init__.py
├── core.py
├── data
├── lib
│   └── mods.py
```

to 
```
membrane_curvature
├── __init__.py
├── core.py
├── data
├── analysis
│   └── Curvature.py. --> this would contain H, K
│   └── Surface.py. --> this would contain z_ref, derive_surface, normalized_grid
```
With `lib` and `mods`  gone, the explicit import would look like

```
from membrane_curvature.analysis.Curvature import mean_curvature, gaussian_curvature
from membrane_curvature.analysis.Surface import normalized_grid, derive_surface, get_z_surface
```
Otherwise, `from membrane_curvature.lib.mods import mean_curvature, gaussian_curvature, normalized_grid, derive_surface, get_z_surface` will solve this. 

Any suggestions @lilyminium?

**Comment by lilyminium** [comment]
What do you envision being in `core.py`?

If you only have two files in `analysis`, you may as well have those files in the root level directory as well.

```
membrane_curvature
├── __init__.py
├── core.py
├── data
├── Curvature.py. --> this would contain H, K
├── Surface.py. --> this would contain z_ref, derive_surface, normalized_grid
```

One thing I will say is that it's very uncommon to capitalize module names.

**Comment by ojeda-e** [comment]
Thanks for pointing out capitalization. I left `core.py` but that could be replaced by `base.py` (I don't see any functionality for `core.py` at the moment, but I may be wrong). I added the data folder but not tests etc.  so the tree would look like
```
membrane_curvature
├── __init__.py
├── base.py
├── curvature.py. --> this would contain H, K
├── surface.py. --> this would contain z_ref, derive_surface, normalized_grid
├── data
├── tests
```

**Comment by lilyminium** [comment]
That looks like a good way to deal with it!
