### ISSUE TITLE
Docs not building after renaming.

### ISSUE THREAD

**Issue by ojeda-e** [MDAnalysis/membrane-curvature#24]
`Import membrane_curvature` (Line 16) seems to be the problem. 
Docs build otherwise. 

Any suggestion @lilyminium on how to solve this issue?

**Comment by IAlibay** [comment]
@ojeda-e can you link to where the error occurred?

**Comment by ojeda-e** [comment]
Thanks @IAlibay.

On `docs/`, `make html` fails. I get this error.
```
Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/Users/estefania/opt/anaconda3/envs/membcurv-dev/lib/python3.7/site-packages/sphinx/config.py", line 323, in eval_config_file
    exec(code, namespace)
  File "/Users/estefania/python_playground/membrane-curvature/docs/conf.py", line 16, in <module>
    import membrane_curvature
ModuleNotFoundError: No module named 'membrane_curvature'
```

I did build the docs before pushing the last PR #23 . However, after fetching and rebasing the `main` branch, this error happens. Probably I didn't clean before building again. 

With the change here provided, `make html` works as expected.

**Comment by lilyminium** [comment]
@ojeda-e you might need to `pip uninstall <my_old_mdakit_name>` and `python setup.py develop` this one? I think it might just be installed in your Python environment under a different name

**Comment by ojeda-e** [comment]
Yes, fixed. Thanks! Will close this issue and will close the PR.
