### ISSUE TITLE
Define grid size for different box shapes.

### ISSUE THREAD

**Issue by ojeda-e** [MDAnalysis/membrane-curvature#35]
As pointed out by @orbeckst, after initial refactor in #34 the grid is assumed to be square. The grid should accept at least rectangular shapes.

To do:
- [ ] Define the size of the grid by at least `x` and `y`. 
Suggestion: `box_size = max(u.dimensions[0], u.dimensions[1])`
- [ ] Add `xfail` for  orhtorombic/triclinic box.

**Comment by ojeda-e** [comment]
I think we I can close this issue since we have 
`self.x_range = x_range if x_range else (0, universe.dimensions[0])`
`self.y_range = y_range if y_range else (0, universe.dimensions[1])` 

in `base.py` and respective tests with rectangular box sizes.

Do you agree @orbeckst @IAlibay @lilyminium ? Am I missing something here? Thanks.

**Comment by lilyminium** [comment]
If you add a rectangular grid test then yeah I think this is covered!
