### ISSUE TITLE
Investigate effect of `np.float32` cast in code performance.

### ISSUE THREAD

**Issue by ojeda-e** [MDAnalysis/membrane-curvature#42]
From PR #40 [and comments](https://github.com/MDAnalysis/membrane-curvature/pull/40#issuecomment-873478367).  
Function `derive_surface` includes `factor = np.float32(n_cells / max_width)` in line 30, which is not clear.
Investigate performance of `factor = np.float32(n_cells / max_width)` vs, `factor = n_cells / max_width`.

**Comment by ojeda-e** [comment]
This issue was opened during refactoring.
The previous code used operations with `grid_z_coordinates = np.zeros([n_cells, n_cells])` and   `grid_norm_unit = np.zeros([n_cells, n_cells])`  that initially offered faster calculation by adding `factor = np.float32(n_cells / max_width)`.
Since operations between these arrays are used anymore (it was used in a for loop to iterate over frames [here, in line 57](https://github.com/MDAnalysis/membrane-curvature/pull/40/files) ), IMO this issue makes no sense anymore. Hence, considering closing it.

Any objections @IAlibay @orbeckst @lilyminium?

**Comment by orbeckst** [comment]
Sounds sensible.

**Comment by IAlibay** [comment]
+1 sounds reasonable.

**Comment by ojeda-e** [comment]
Thanks @orbeckst @IAlibay , officially closing this issue.
