### ISSUE TITLE
Exception in `surface.py` is never raised after adding coordinate wrapping.

### ISSUE THREAD

**Issue by ojeda-e** [MDAnalysis/membrane-curvature#50]
After adding PBC/coordinate wrapping and while testing the exception in line 76-77 of `surface.py`, I noticed  `IndexError` is not raised. Issue identified by the message
`AssertionError: Regex pattern 'index is out of bounds' does not match 'index 3 is out of bounds for axis 0 with size 3'.`

If the exception is not raised, should be removed. However, there must be some sort of `IndexError` or `ValueError` raising to notify the user there is a potential loss of information by lack of sampling. 

To fix this issue:
- Figure out if the exception is needed. If not, provide an alternative.
- Add tests to raise the exception if included.

**Comment by orbeckst** [comment]
From what you're writing it looks to me that an IndexError is raised but that the _message_ is not the one you were expecting.

**Comment by lilyminium** [comment]
+ 1 — regex stands for regular expression. (https://en.m.wikipedia.org/wiki/Regular_expression ) The pattern matching isn’t working because there are extra values in the actual error message

**Comment by ojeda-e** [comment]
Sorry, I should have been tired when this happened. Never mind. Can I close this?
