### ISSUE TITLE
Documentation badge doesn't point to helpful docs

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/membrane-curvature#53]
The documentation badge currently points to the contents of `docs/`, which is just a page telling you how to compile the membrane curvature docs: https://www.mdanalysis.org/membrane-curvature/

Could you please change the link to ReadTheDocs, which is currently working documentation? https://membrane-curvature.readthedocs.io/en/latest/

**Comment by ojeda-e** [comment]
Thanks for catching this @lilyminium. :)
