### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/membrane-curvature#54]
Could you please add installation instructions? Edit: typically installation instructions are given both in the root repo README.md, and in the documentation on ReadTheDocs. At the moment, as a new user, I'm not sure how to install and use your code. There have not been any releases yet, so people will have to build from source. I usually put my dependencies into another yaml file instead of re-using my test environment, because that has extra packages such as pytest. For examples, yours could look like:

```
name: membrane-curvature
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy

    # Pip-only installs
  - pip:
    - MDAnalysis==2.0.0b0
```

If you save that as `environment.yml` in `devtools/conda-envs`, building from source would look like:

```
git clone https://github.com/MDAnalysis/membrane-curvature.git
cd membrane-curvature
conda env create -f devtools/conda-envs/environment.yaml
conda activate membrane-curvature
python setup.py install
```

Once packages are created for Pypi and conda, those instructions can be added too.

**Comment by ojeda-e** [comment]
( Sorry @lilyminium, I'm going to make this issue a bit messy by changing the whole README. :) )
While this issue is open, on top of the installation instructions add sections for:

- [ ] Usage
- [ ] License
- [ ] Documentation
- [ ] Features
