### ISSUE TITLE
Set up documentation

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/membrane-curvature#6]
A documentation badge is added in #4, but the link it points to https://www.mdanalysis.org/membrane-curvature/ doesn't actually exist yet. I've set up the ReadTheDocs webhook at https://membrane-curvature.readthedocs.io/en/latest/ for now. We have a couple options for the final docs:
* pointing RTD to something like membrane-curvature.mdanalysis.org (I don't think RTD will accept https://www.mdanalysis.org/membrane-curvature/)
* Setting up a gh-pages branch like https://github.com/MDAnalysis/pmda , which will automatically serve docs at https://www.mdanalysis.org/membrane-curvature/ (as is done for the main repository and user guide documentation)

Any opinions @ojeda-e @orbeckst @fiona-naughton @IAlibay ?

**Comment by orbeckst** [comment]
gh-pages branch, please — we have been fairly restrictive in what we use for top-level names; all our other projects are showing up as www.mdanalysis.org/NAME so I am in favor of doing the same for this project
