### ISSUE TITLE
consistent license

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/membrane-curvature#60]
As noted by @IAlibay in comments on PR #59 , there's an inconsistency in the licensing:
- docs say GPL v3 (see PR #59)
- LICENSE file says MIT
- setup.py says MIT 

Obviously, this needs to be consistent.

The choice of license leads us into hotly debated territory that requires lawyers (at least in principle). MDAnalysis itself is licensed under "GPL v2 or any later version". This means that GPL v3 is an allowed license.

@ojeda-e you need to set your license.

**Comment by orbeckst** [comment]
What I wrote in the main issue report should not be controversial, namely that you can just choose GPL v3 (or GPL v2) and everything is fine.

DISCLAIMER: **First of: I am not a lawyer so any comments/recommendations that I am making are not be taken as any form of legal advice.** (I am not joking here, technically speaking the NumFOCUS lawyers have a say here.)

It is less clear that you're actually free to choose MIT. My understanding is that at least the Free Software Foundation says that as soon as your code says `import MDAnalysis` (and you use the MDAnalysis API directly, i.e., Universe, AtomGroup, AnalysisBase) you're bound by the copy-left of the GPL under which MDAnalysis is published and you _must_ also use GPL. 

Some of the @MDAnalysis/coredevs might have different opinions.

**Comment by IAlibay** [comment]
(disclaimer: not a lawyer)

My take is that the whole thing is quite murky. Going with @orbeckst's suggestion of GPLv3 is probably the safest thing to do for now given you'd want to do a release by the end of GSoC. Once we get confirmation from an actual lawyer, given that there are few contributors to this repo, I _think_ you could then just change the license if needed?

**Comment by ojeda-e** [comment]
Thanks for your comments @orbeckst @IAlibay, I addressed this issue in #61
