### ISSUE TITLE
Sign of mean curvature

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/membrane-curvature#70]
Related to #69: I think the sign of the mean curvature is reversed here compared convention.

Conventionally I think we use the upward-pointing Z-axis as the membrane normal. With that, you can use [this definition of the mean curvature](https://en.wikipedia.org/wiki/Mean_curvature#Surfaces_in_3D_space) (as you do). But I think you've added an extra negative. Should that be there?

**Comment by ojeda-e** [comment]
Thanks, @lilyminium for pointing this out! I'll fix it ASAP! :)
