### ISSUE TITLE
register membrane-curvature as an MDAKit

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/membrane-curvature#92]
Now that MDAKits are live to roll we should work towards registering `membrane-curvature` as an MDAKit!

See the [blog post](https://www.mdanalysis.org/2022/08/24/mdakits-intro/) for more info. 

AFAIK `membrane-curvature` already meets all the requirements listed in the [white paper](https://figshare.com/articles/preprint/MDAKits_Supporting_and_promoting_the_development_of_community_packages_leveraging_the_MDAnalysis_library/20520726/1).

**Comment by IAlibay** [comment]
@hmacdope let's not rush, the registry isn't here yet.

**Comment by hmacdope** [comment]
Ah right, sorry.

**Comment by hmacdope** [comment]
@MDAnalysis/coredevs can someone with write access make me a maintainer so I can add this to 3.0 board.

**Comment by orbeckst** [comment]
I added @hmacdope as a maintainer. Please let me know if this is not working.

**Comment by orbeckst** [comment]
The registry is life and we have documentation on how to add the kit.

**Comment by IAlibay** [comment]
I'm assigning @fiona-naughton and @ianmkenney to add this to the registry - we need this done before the EOSS4 report deadline.

**Comment by IAlibay** [comment]
To get things moving, I'm doing this myself: https://github.com/MDAnalysis/MDAKits/pull/106

**Comment by orbeckst** [comment]
completed with https://github.com/MDAnalysis/MDAKits/pull/106 and available as https://mdakits.mdanalysis.org/membrane-curvature.html
